from django.db import models

# Create your models here.
class vitModel(models.Model):

    age = models.FloatField()
    bmi = models.FloatField()
    alcohol_consumption = models.FloatField()
    sun_exposure = models.FloatField()
    income_level = models.FloatField()
    latitude_region = models.FloatField()
    vitamin_a_percent_rda = models.FloatField()
    vitamin_c_percent_rda = models.FloatField()
    vitamin_d_percent_rda = models.FloatField()
    vitamin_e_percent_rda = models.FloatField()
    vitamin_b12_percent_rda = models.FloatField()
    folate_percent_rda = models.FloatField()
    calcium_percent_rda = models.FloatField()
    iron_percent_rda = models.FloatField()
    hemoglobin_g_dl = models.FloatField()
    serum_vitamin_d_ng_ml = models.FloatField()
    serum_vitamin_b12_pg_ml = models.FloatField()
    serum_folate_ng_ml = models.FloatField()
    symptoms_count = models.IntegerField()
    has_night_blindness = models.IntegerField()
    has_fatigue = models.IntegerField()
    has_bleeding_gums = models.IntegerField()
    has_bone_pain = models.IntegerField()
    has_muscle_weakness = models.IntegerField()
    has_numbness_tingling = models.IntegerField()
    has_memory_problems = models.IntegerField()
    has_pale_skin = models.IntegerField()
    gender = models.CharField(max_length=20)
    smoking_status = models.CharField(max_length=50)
    exercise_level = models.CharField(max_length=50)
    diet_type = models.CharField(max_length=50)
